version: '3.8'

networks: 
  bubble:
    external: true

services:

  fitmap.function.set-roles:
    container_name: fitmap.function.set-roles
    image: maven:3-adoptopenjdk-11-openj9
    working_dir: /app
    networks:
      - bubble
    ports:
      - "9050:8080"
    volumes:
      - $PWD:/app
      - ~/.m2:/root/.m2
    entrypoint: mvn function:run -Drun.functionTarget=com.fitmap.function.setroles.SetRolesFunction
